### ISSUE TITLE
NPM version 12.6 

### ISSUE THREAD

**Issue by levonmanucharian** [brianreavis/selectize.js#1816]
When trying to add the selectize via npm, the npm install selectize adds the version 12.6, no option to install the latest version. Any chance you could update the release version accordingly? Thanks.

**Comment by risadams** [comment]
yes.  switch to using `npm i @selectize/selectize`

**Comment by FritzHerbers** [comment]
@risadams 
Since a year I am checking for newer releases: https://github.com/selectize/selectize.js/issues/1619

That since half a year the npm packagename changed I haven't noticed (first release 0.13.4). Looking at the weekly downloads for sure not that many developers noticed the change.

Make this more dominant in the readme.
